import YAML from "yaml";
import type { DeploymentEnv } from "./env.js";
import type { PoolConfig, ResolvedConfig } from "./config.js";

export function renderCompose(
  config: ResolvedConfig,
  env: DeploymentEnv
): string {
  const services = Object.fromEntries(
    config.pools.flatMap((pool) =>
      Array.from({ length: pool.size }, (_, index) => {
        const serviceName = buildServiceName(pool, index);
        return [serviceName, renderService(pool, index)];
      })
    )
  );

  const document = new YAML.Document({
    name: env.composeProjectName,
    services
  });

  return [
    "# Generated by pnpm render-compose --output docker-compose.generated.yml",
    "# Shell-only runners: no Docker socket, no privileged mode, no published ports.",
    document.toString().trimEnd()
  ].join("\n");
}

export function buildServiceName(pool: PoolConfig, index: number): string {
  return `${pool.key}-runner-${formatIndex(index)}`;
}

export function buildRunnerName(pool: PoolConfig, index: number): string {
  return buildServiceName(pool, index);
}

export function buildRunnerStateDir(pool: PoolConfig, index: number): string {
  return `${pool.runnerRoot}/runner-${formatIndex(index)}`;
}

function renderService(pool: PoolConfig, index: number): Record<string, unknown> {
  const runnerStateDir = buildRunnerStateDir(pool, index);
  const environment: Record<string, string> = {
    GITHUB_PAT: "${GITHUB_PAT}",
    GITHUB_API_URL: "${GITHUB_API_URL:-https://api.github.com}",
    GITHUB_ORG: pool.organization,
    RUNNER_SCOPE: "organization",
    RUNNER_NAME: buildRunnerName(pool, index),
    RUNNER_GROUP: pool.runnerGroup,
    RUNNER_LABELS: pool.labels.join(","),
    RUNNER_VISIBILITY: pool.visibility,
    RUNNER_REPOSITORY_ACCESS: pool.repositoryAccess,
    RUNNER_STATE_DIR: runnerStateDir,
    RUNNER_LOG_DIR: `${runnerStateDir}/logs`,
    RUNNER_WORK_DIR: "/tmp/github-runner-work",
    RUNNER_TEMP: "/tmp/github-runner-temp",
    RUNNER_TOOL_CACHE: "/opt/hostedtoolcache",
    AGENT_TOOLSDIRECTORY: "/opt/hostedtoolcache",
    RUNNER_EPHEMERAL: "true",
    RUNNER_DISABLE_UPDATE: "true"
  };

  if (pool.repositoryAccess === "selected") {
    environment.RUNNER_ALLOWED_REPOSITORIES = pool.allowedRepositories.join(",");
  }

  const service: Record<string, unknown> = {
    image: pool.imageRef,
    container_name: buildServiceName(pool, index),
    hostname: buildRunnerName(pool, index),
    restart: "unless-stopped",
    stop_grace_period: "2m",
    environment,
    volumes: [`${runnerStateDir}:${runnerStateDir}`],
    security_opt: ["no-new-privileges:true"],
    cap_drop: ["ALL"],
    labels: {
      "com.synology-gh-runner.pool": pool.key,
      "com.synology-gh-runner.visibility": pool.visibility,
      "com.synology-gh-runner.repository-access": pool.repositoryAccess,
      "com.synology-gh-runner.allowed-repositories":
        pool.repositoryAccess === "all"
          ? "all"
          : pool.allowedRepositories.join(","),
      "com.synology-gh-runner.shell-only": "true"
    }
  };

  if (pool.architecture !== "auto") {
    service.platform = `linux/${pool.architecture}`;
  }

  if (pool.resources.cpus) {
    service.cpus = pool.resources.cpus;
  }

  if (pool.resources.pidsLimit !== undefined) {
    service.pids_limit = pool.resources.pidsLimit;
  }

  if (pool.resources.memory) {
    service.mem_limit = pool.resources.memory;
  }

  return service;
}

function formatIndex(index: number): string {
  return String(index + 1).padStart(2, "0");
}
