version: 1
image:
  repository: ghcr.io/omt-global/synology-github-runner
  tag: 0.1.6
pools:
  - key: synology-private
    visibility: private
    organization: omt-global
    runnerGroup: synology-private
    repositoryAccess: all
    labels:
      - synology
      - shell-only
      - private
    size: 2
    architecture: auto
    runnerRoot: ${SYNOLOGY_RUNNER_BASE_DIR}/pools/synology-private
    resources:
      memory: 2g
  - key: synology-public
    visibility: public
    organization: omt-global
    runnerGroup: synology-public
    repositoryAccess: selected
    allowedRepositories:
      - omt-global/axiom
      - omt-global/synology-github-runner
    labels:
      - synology
      - shell-only
      - public
    size: 2
    architecture: auto
    runnerRoot: ${SYNOLOGY_RUNNER_BASE_DIR}/pools/synology-public
    resources:
      memory: 1g
